Initial check-in for ANF Snapshot Policy in Azure CLI
Azure-Samples/netappfiles-cli-snapshot-policy-script-sample pull request #1
Opened 2021-02-19 01:24 UTC by AdelGhabboun

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[x] Other... Please describe: Script Sample
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2021-02-23 21:42 UTC, audunn requested changes

2021-02-23 21:42 UTC, audunn commented on README.md
> +# Azure NetAppFiles script Sample - Snapshot Policy for Azure CLI
Documentation folks may complain, I think they prefer we use: `Azure NetApp Files`

2021-02-25 22:19 UTC, AdelGhabboun commented on README.md
> +# Azure NetAppFiles script Sample - Snapshot Policy for Azure CLI
I agree

2021-03-16 16:48 UTC, paulomarquesc commented on src/create-anf-snapshot-policy.sh
> +            }
I think this can be simplified as:

```
 az netappfiles account show --ids $_RESOURCE_ID || break
```

2021-03-16 16:48 UTC, paulomarquesc commented on src/create-anf-snapshot-policy.sh
> +    _SPACED_RESOURCE_ID=$_RESOURCE_ID;_SPACED_RESOURCE_ID="${_RESOURCE_ID//\// }"
We don't need _SPACED_RESOURCE_ID, since the variable is local _RESOURCE_ID, you can do the spacing directly on _RESOURCE_ID.

2021-03-16 21:53 UTC, merged